FORMAT: 1A
HOST: https://politico-api-database.herokuapp.com

# Politico app

Politico is a simple API allowing users vote in their candidates of choice.

### Create Account [/api/v2/auth/signup]

#### SignUp [POST]

+ Request (application/json)

        {
            "firstname" : "Peter",
            "lastname" : "Gitundu",
            "email" : "peter@gmail.com",
            "password": "Peter20930988",
            "phoneNumber" : "0720930981",
            "passportUrl" : "https://www.peter.com",
            "role" : "user"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/auth/signup

    + Body

            {
                "message": "Account created successfully",
                "status": "201",
                "user": {
                    "email": "peter@gmail.com",
                    "firstname": "Peter",
                    "lastname": "Gitundu",
                    "passporturl": "https://www.peter.com",
                    "password": "pbkdf2:sha256:50000$KgzDWp19$900f65b32441686bc954a319a6dadfeb166eab9bb20632d53cc9c160d1dbf15d",
                    "phonenumber": "0720930981",
                    "role": "user"
                }
            }
            
            
            
            
### Login [/api/v2/auth/login]

#### SignIn [POST]

+ Request (application/json)

        {
            "email": "peter@gmail.com",
            "password": "Peter20930988"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/auth/login

    + Body

            {
                "message": "successfully logged in peter@gmail.com",
                "status": "200",
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTA4MDEyMTgsIm5iZiI6MTU1MDgwMTIxOCwianRpIjoiNTEyMmMzNDktZTEwNS00ODNkLTg0NmItNGI0OTE2MTg3NmJkIiwiZXhwIjoxNTUwODAyMTE4LCJpZGVudGl0eSI6InBldGVyQGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.JD8FGlNBTWlxSdZsorddNLc5KmbLI5MSkDsXuaEPk7Y"
            }
            
### Get all Users [/api/v2/users]    
            
#### Get Users  [GET]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/users
            
    + Body

            {
                "message": "success",
                "status": "200",
                "users": [
                    {
                        "date": null,
                        "email": "peter@gmail.com",
                        "firstname": "Peter",
                        "lastname": "Gitundu",
                        "passporturl": "https://www.peter.com",
                        "password": "pbkdf2:sha256:50000$KgzDWp19$900f65b32441686bc954a319a6dadfeb166eab9bb20632d53cc9c160d1dbf15d",
                        "phonenumber": "0720930981",
                        "role": "user",
                        "user_id": 1
                    }
                ]
            }
            
### Specific User [/api/v2/users/{user_id}]

+ Parameters
    + user_id (number)

#### Get User  [GET]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/users/{user_id}
    
    + Body

            {
                "message": "success",
                "status": "200",
                "user": {
                    "date": null,
                    "email": "peter@gmail.com",
                    "firstname": "Peter",
                    "lastname": "Gitundu",
                    "passporturl": "https://www.peter.com",
                    "password": "pbkdf2:sha256:50000$KgzDWp19$900f65b32441686bc954a319a6dadfeb166eab9bb20632d53cc9c160d1dbf15d",
                    "phonenumber": "0720930981",
                    "role": "user",
                    "user_id": 1
                }
            }
            
#### Make Admin [PUT]

+ Request (application/json)

        {
            "role": "admin"
        }

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/users/{user_id}

    + Body

            {
                "message": "user successfully promoted to be an admin",
                "new_role": {
                    "role": "admin"
                },
                "status": "200"
            }
        

### Offices [/api/v2/offices]

#### Create office [POST]

+ Request (application/json)

        {
            "category": "executive",
            "name": "presidential"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/offices

    + Body

            {
                "message": "office created successfully!",
                "office": {
                    "category": "federal",
                    "name": "womenrep"
                },
                "status": "201"
            }
            
#### Get all offices  [GET]

+ Response 200 (application/json)

            {
                "message": "success",
                "offices": [
                    {
                        "category": "federal",
                        "name": "womenrep",
                        "office_id": 1
                    }
                ],
                "status": "200"
            }
        





### Specific Office [/api/v2/offices/{office_id}]

+ Parameters
    + office_id (number)

#### Get One office  [GET]

+ Response 200 (application/json)
    
    + Body

            {
                "message": "success",
                "office": {
                    "category": "federal",
                    "name": "womenrep",
                    "office_id": 1
                },
                "status": "200"
            }
            
#### Edit office [PUT]

+ Request (application/json)

        {
            "category": "executive",
            "name": "presidential"
        }

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/offices/{office_id}

    + Body

            {
                "message": "office updated successfully",
                "new_office": {
                    "category": "federal",
                    "name": "mca"
                },
                "status": "200"
            }

#### Delete One office [DELETE]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/offices/{office_id}/delete

    + Body
    
            {
                "message": "office deleted",
                "status": "200"
            }



### Parties [/api/v2/parties]

#### Create party [POST]

+ Request (application/json)

        {
            "name": "executive",
            "hqAddress": "presidential",
            "logoUrl": "https://www.w3schools.com"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/parties

    + Body

            {
                "message": "party created successfully!",
                "party": {
                    "hqaddress": "nniversay",
                    "logourl": "https://www.ns.com",
                    "name": "OM"
                },
                "status": "201"
            }
            
#### Get all parties  [GET]

+ Response 200 (application/json)

            {
                "message": "success",
                "parties": [
                    {
                        "hqaddress": "nniversay",
                        "logourl": "https://www.ns.com",
                        "name": "OM",
                        "party_id": 1
                    }
                ],
                "status": "200"
            }




### Specific Party [/api/v2/parties/{party_id}]

+ Parameters
    + party_id (number)

#### Get One party  [GET]

+ Response 200 (application/json)
    
    + Body

            {
                "message": "success",
                "party": {
                    "hqaddress": "nniversay",
                    "logourl": "https://www.ns.com",
                    "name": "OM",
                    "party_id": 1
                },
                "status": "200"
            }
            
#### Edit party [PUT]

+ Request (application/json)

        {
            "name": "executive",
            "hqAddress": "presidential",
            "logoUrl": "https://www.w3schools.com"
        }

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/parties/{party_id}

    + Body

            {
                "message": "party updated successfully",
                "new_party": {
                    "hqaddress": "nnivsay",
                    "logourl": "https://www.s.com",
                    "name": "NASA"
                },
                "status": "200"
            }

#### Delete One party [DELETE]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/parties/{party_id}

    + Body
    
            {
                "message": "party deleted",
                "status": "200"
            }
            
### Candidates [/api/v2/candidates/register]

#### Promote User [POST]

+ Request (application/json)

        {
            "office": "1",
            "candidate": "1",
            "party": "1"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/candidates/register

    + Body

            {
                "candidate": {
                    "candidate": 2,
                    "office": 3,
                    "party": 2
                },
                "message": "user promoted successfully",
                "status": "201"
            }
            
### User Vote [/api/v2/vote]

#### Vote [POST]

+ Request (application/json)

        {
            "createdBy": "1",
            "office": "1",
            "candidate": "1"
        }

+ Response 201 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v2/vote

    + Body

            {
                "message": "voted successfully",
                "status": "201",
                "vote": {
                    "candidate": 1,
                    "createdby": 2,
                    "office": 3
                }
            }
            
#### Get Results  [GET]

+ Response 200 (application/json)

    + Headers

            Location: /api/v2/vote/results
            
    + Body

                {
                    "message": "success",
                    "office": {
                        "candidate": 1,
                        "count": 1
                    },
                    "status": "200"
                }
            
### File Petitions [/api/v2/petitions]

#### Petitions [POST]

+ Request (application/json)

        {
            "createdBy": "Harun",
            "office": "Presidential",
            "body": "This was a fraud"
        }

+ Response 201 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v2/petitions

    + Body

            {
                "message": "petition filed successfully"
            }